### ISSUE TITLE
[FEA] Tracker for mdspan serialization and copy

### ISSUE THREAD

**Issue by hcho3** [rapidsai/raft#1017]
Following up with #752.

Design choices
* Provide efficient serializers for mdspan's with C and Fortran layouts. Mdspan's can have an arbitrary layouts which makes it hard to serialize efficiently.
* Provide a copy operator so that users can transform their mdspans into C or Fortran layouts.
  - In general, provide a generic fallback implementation (possibly suboptimal), and provide specialized versions of `copy` that are optimized for certain use cases.
* Adopt [the NumPy format](https://numpy.org/doc/1.23/reference/generated/numpy.lib.format.html) for easy inter-op with NumPy and other array libraries.
* Also expose `__array_interface__` for zero-copy serialization

TODO's

- [ ] Implement a copy operation between two mdspan's
  * [x] Implement fallback copy operation to copy elements between two mdspan's on the host memory
  * [ ] Implement fallback copy operation to copy elements between two mdspan's on the device memory
  * [ ] Implement wrappers for copying Fortran-, C-layout, or strided arrays between the host and device memory
- [ ] Implement serializer for mdspan's with Fortran and C layouts
  * [ ] Serialize to `std::ostream`
  * [ ] Serialize to container iterator
  * [ ] Serialize via `__array_interface__`
