### ISSUE TITLE
[FEA] Solvers API Tracker Issue

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1131]
- [ ] LOBPCG (https://github.com/rapidsai/raft/issues/1129)
- [ ] Cholesky (https://github.com/rapidsai/raft/issues/929)
- [ ] CG (https://github.com/rapidsai/raft/issues/672)
- [ ] L-BFGS-B (https://github.com/rapidsai/raft/issues/671)
- [ ] SLSQP (https://github.com/rapidsai/raft/issues/669)
- [ ] Lanczos (https://github.com/rapidsai/raft/issues/379 and https://github.com/rapidsai/raft/issues/313)
- [ ] Port cuML solvers (https://github.com/rapidsai/raft/issues/1130)
