### ISSUE TITLE
[FEA] Promote CAGRA from experimental

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#1605]
Tracking tasklist to promote CAGRA from experimental. Note that this is a subset of the tasks in https://github.com/rapidsai/raft/issues/1392.

cc @tfeher @enp1s0 @teju85 @wphicks 

- [ ] Shrink CAGRA binary size (https://github.com/rapidsai/raft/issues/1459)
- [ ] Compose CAGRA from RAFT primitives/helpers (https://github.com/rapidsai/raft/issues/1604)
- [x] Avoid unecessary device memory copies (https://github.com/rapidsai/raft/issues/1479)
- [x] Use rmm to fix stream ordering in `prune` (https://github.com/rapidsai/raft/issues/1461)
- [x] Re-introduce template instantiations to improve compile times (https://github.com/rapidsai/raft/issues/1443)
- [x] int8/uint8 distance scaling (https://github.com/rapidsai/raft/issues/1457)
- [x] Add cagra to ANN benchmarks (https://github.com/rapidsai/raft/pull/1552)
- [x] Add CAGRA gbench (https://github.com/rapidsai/raft/pull/1496)
- [x] Fix multi-CTA accuracy bug (https://github.com/rapidsai/raft/issues/1575)

**Comment by enp1s0** [comment]
I'm now working on https://github.com/rapidsai/raft/issues/1575.
