### ISSUE TITLE
[FEA] Establish RAFT API contract

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#360]
Tracking issue for updating the public API functions to adhere to the agreed-upon contract. This includes the ongoing refactor work kicked off by @divyegala. 

- [x] Add handle and remove explicit stream
- [x] Use common storage / representation formats
- [x] Consistency in ordering of arguments (ins vs outs, etc...)

**Comment by cjnolet** [comment]
Marking the subtasks done here since we already have alignment on them. Remaining work will be completed in #535
