### ISSUE TITLE
[FEA] Implement new API functions using `mdspan` 

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/raft#535]
Now that we have `mdspan` and `mdarray` in RAFT, we are able to start implementing our new public API contract facades with them. 

To start, we can add new functions that assume the underlying layouts are contiguous, deprecate the old functions, and then as we iterate on the `mdspan` and `mdarray` and use them in more in device functions, we can eventually support non-contiguous layouts. 

Ideally we would be consistent about the ordering of arguments to the new functions. We should start using `std::optional` for any optional arguments (instead of null pointers) and perhaps follow Thrust's format of accepting inputs before outputs (raft handle should always be the first argument). 

Namespaces to add the new functions:
- [x] raft::cluster (Mickael)
- [x] raft::distance (Corey)
- [x] raft::random (Mark)
- [x] raft::linalg (Divye)
- [X] raft::matrix (Corey) 
- [x] raft::stats (Mickael)
- [x] raft::spatial::knn (Corey) 

It might also make sense to break these up so different people can take on a couple namespaces. This could help 1) more developers getting quickly spun up on mdarray/mdspan, and 2) getting these knocked out more quickly while folks are able to work on different parts concurrently. 

This issue will also close #360
